/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.uas;

/**
 *
 * @author calvi
 */
public class ProjectUASVersiLain extends javax.swing.JFrame {

    /**
     * Creates new form ProjectUASVersiLain
     */
    public ProjectUASVersiLain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbproduk = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txthargasatuan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnama1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtjumlah = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtdiskon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txthargatotal = new javax.swing.JTextField();
        btncekdiskon = new javax.swing.JButton();
        btncektotalbayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Masukkan Nama Anda :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Pilih Produk :");

        cmbproduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Topi", "Baju", "Celana", "Sepatu" }));
        cmbproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbprodukActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Harga Satuan :");

        txthargasatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargasatuanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Masukkan Alamat Anda :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Jumlah Pesanan :");

        txtjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Diskon :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("Total Harga :");

        txthargatotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargatotalActionPerformed(evt);
            }
        });

        btncekdiskon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btncekdiskon.setText("Cek Diskon");
        btncekdiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncekdiskonActionPerformed(evt);
            }
        });

        btncektotalbayar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btncektotalbayar.setText("Cek Total Bayar");
        btncektotalbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncektotalbayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnama1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtdiskon, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtjumlah, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txthargatotal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txthargasatuan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbproduk, javax.swing.GroupLayout.Alignment.LEADING, 0, 194, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btncekdiskon)
                                    .addComponent(btncektotalbayar))))))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txthargasatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btncekdiskon)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txthargatotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncektotalbayar))
                .addContainerGap(298, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbprodukActionPerformed
        // TODO add your handling code here:
        String produk;
        double hargasatuan;
        
        produk = String.valueOf(cmbproduk.getSelectedItem());
        
        if (produk.equals("Topi")){
            hargasatuan = 10000;
        } else if (produk.equals("Baju")){
            hargasatuan = 20000;
        } else if (produk.equals("Celana")){
            hargasatuan = 30000;
        } else {
            hargasatuan = 40000;
        }
        
        txthargasatuan.setText(""+hargasatuan);
    }//GEN-LAST:event_cmbprodukActionPerformed

    private void txthargasatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargasatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargasatuanActionPerformed

    private void txtjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahActionPerformed

    private void btncekdiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncekdiskonActionPerformed
        // TODO add your handling code here:
        double hargasatuan,diskon;
        int jumlah;
        
        jumlah = Integer.parseInt(txtjumlah.getText());
        hargasatuan = Double.parseDouble(txthargasatuan.getText());
        
        if (jumlah <5){
            diskon = 0;
        } else if (jumlah >5 && jumlah == 20){
            diskon = hargasatuan * 0.1;
        } else if (jumlah >20 && jumlah == 50){
            diskon = hargasatuan * 0.2;
        } else {
            diskon = hargasatuan * 0.3;
        }
        
        txtdiskon.setText(""+diskon);
    }//GEN-LAST:event_btncekdiskonActionPerformed

    private void btncektotalbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncektotalbayarActionPerformed
        // TODO add your handling code here:
        double hargasatuan,diskon,totalharga;
        int jumlah;
        
        hargasatuan = Double.parseDouble(txthargasatuan.getText());
        jumlah = Integer.parseInt(txtjumlah.getText());
        diskon = Double.parseDouble(txtdiskon.getText());
        
        totalharga = (hargasatuan * jumlah) - diskon;
        txthargatotal.setText(""+totalharga);
    }//GEN-LAST:event_btncektotalbayarActionPerformed

    private void txthargatotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargatotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargatotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectUASVersiLain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectUASVersiLain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectUASVersiLain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectUASVersiLain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectUASVersiLain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncekdiskon;
    private javax.swing.JButton btncektotalbayar;
    private javax.swing.JComboBox<String> cmbproduk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtdiskon;
    private javax.swing.JTextField txthargasatuan;
    private javax.swing.JTextField txthargatotal;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtnama1;
    // End of variables declaration//GEN-END:variables
}
